# Demo WhileActivity
The while activity executes a **sub_process** until a **condition_event** is fulfilled. The condition event can be formulated based on the expression language documented in the project.

In [5]:
import datetime, time
import simpy

import pandas as pd
import openclsim.core as core
import openclsim.model as model
import openclsim.plot as plot

# setup environment
simulation_start = 0
my_env = simpy.Environment(initial_time=simulation_start)
registry = {}

## Definition of while activity with a nested basic activity
This example has a constraint that the activity while has to be completed. Thus, the activity while is terminating after the activity while has been completed. This is impossible, thus this expression guarantees an infinte loop, which will be limited in the simulation run parameter below.

In [2]:
basic_activity_data = {
    "env": my_env,
    "name": "Basic activity",
    "ID": "6dbbbdf7-4589-11e9-bf3b-b469212bff5b",  # For logging purposes
    "registry": registry,
    "duration": 14,
    "postpone_start": True,
}
activity = model.BasicActivity(**basic_activity_data)

while_data = {
    "env": my_env,  # The simpy environment defined in the first cel
    "name": "while",  # We are moving soil
    "ID": "6dbbbdf7-4589-11e9-bf3b-b469212bff5g",  # For logging purposes
    "registry": registry,
    "sub_process": activity,
    "condition_event": [{"type":"activity", "name": "while", "state":"done"}],
    "postpone_start": False,
}
while_activity = model.WhileActivity(**while_data)

## Run simulation
Since this is an endless loop the execution is constrained to a time limit of 100 time units.

In [3]:
my_env.run(until=100)

In [8]:
display(plot.get_log_dataframe(while_activity, [activity, while_activity]))